-- Migration 002: Default configuration data
-- Seeds default dropdown options and branding/SMTP placeholder rows.
-- Idempotent: safe to re-run, will not duplicate rows.

BEGIN;

-- Default Purpose options
INSERT INTO purpose_options (label, sort_order) VALUES
    ('Bill Pay', 1),
    ('Enquiry', 2),
    ('Complaint', 3),
    ('Purchase', 4),
    ('Meeting', 5),
    ('Interview', 6),
    ('Donation', 7),
    ('Other', 8)
ON CONFLICT DO NOTHING;

-- Default Enquiry Type options
INSERT INTO enquiry_type_options (label, sort_order) VALUES
    ('Cable TV', 1),
    ('Internet', 2),
    ('Solar', 3),
    ('CCTV', 4),
    ('Automation', 5),
    ('Networking', 6),
    ('Others', 7)
ON CONFLICT DO NOTHING;

-- Default Meeting Person options
INSERT INTO meeting_person_options (label, sort_order) VALUES
    ('Jacob', 1),
    ('Sugesh', 2),
    ('Jaison', 3),
    ('Anusha', 4),
    ('Jeeshma', 5),
    ('Others', 6)
ON CONFLICT DO NOTHING;

-- Default branding row
INSERT INTO branding_settings (id, org_name, report_header, report_footer)
VALUES (1, 'Your Organization', 'Visitor & Call Log Report', 'Generated by Visitor Register & Call Log System')
ON CONFLICT (id) DO NOTHING;

-- Default (empty) SMTP settings row
INSERT INTO smtp_settings (id, security) VALUES (1, 'none')
ON CONFLICT (id) DO NOTHING;

-- Default admin user: username "admin", password "admin123" (bcrypt hash below)
-- IMPORTANT: change this password immediately after first login.
-- Hash corresponds to bcrypt("admin123", 10 rounds).
INSERT INTO users (username, password_hash, full_name, role)
VALUES ('admin', '$2b$10$jGjZObQvczlap04gVHcpVuvTEraosKhMpaN4ZJdPm84Ymj/NWWTDm', 'Administrator', 'admin')
ON CONFLICT (username) DO NOTHING;

INSERT INTO schema_migrations (version) VALUES ('002_seed_defaults') ON CONFLICT DO NOTHING;

COMMIT;
