import { useState } from 'react';
import { api } from '../api/client';
export default function DataImport(){
 const [type,setType]=useState('visitors'),[file,setFile]=useState(null),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(null);
 async function encode(f){const b=await f.arrayBuffer();let bin='';const bytes=new Uint8Array(b);for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(bin)}
 async function previewFile(){if(!file)return;setBusy(true);setMsg(null);try{const fileBase64=await encode(file);setPreview(await api.uploadJson('/import/preview',{type,filename:file.name,fileBase64}));}catch(e){setMsg({type:'error',text:e.message})}finally{setBusy(false)}}
 async function commit(){if(!file)return;setBusy(true);setMsg(null);try{const fileBase64=await encode(file);const r=await api.uploadJson('/import/commit',{type,filename:file.name,fileBase64});setMsg({type:'success',text:`Import complete: ${r.imported} imported, ${r.failed} failed.`});setPreview(null);setFile(null);}catch(e){setMsg({type:'error',text:e.message})}finally{setBusy(false)}}
 return <div className="card"><h3 style={{marginTop:0}}>Historical Excel Import</h3>{msg&&<div className={`alert ${msg.type}`}>{msg.text}</div>}<div className="form-grid"><div><label>Import type</label><select value={type} onChange={e=>{setType(e.target.value);setPreview(null)}}><option value="visitors">VISITOR REGISTER</option><option value="calllog">CALL LOG</option></select></div><div><label>Excel file (.xlsx)</label><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null)}}/></div></div><p className="muted">Excel dates/times are treated as Asia/Kolkata (IST). Only the first worksheet is imported.</p><div className="actions"><button className="primary" disabled={!file||busy} onClick={previewFile}>{busy?'Processing…':'Preview & Validate'}</button></div>{preview&&<div className="report-preview"><p><strong>Sheet:</strong> {preview.sheet} &nbsp; <strong>Rows:</strong> {preview.totalRows}</p><table><thead><tr><th>Row</th><th>Status</th><th>Data</th></tr></thead><tbody>{preview.preview.map((r)=><tr key={r.row}><td>{r.row}</td><td>{r.errors.length?'Error':'OK'}</td><td>{r.errors.length?r.errors.join('; '):JSON.stringify(r.data)}</td></tr>)}</tbody></table><div className="actions"><button className="primary" disabled={busy} onClick={commit}>Confirm Import</button></div></div>}</div>
}
